version : "3.9"
services:
  db:
    image : postgres:15
    
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pura_belanda_data:/var/lib/postgresql/data

volumes:
  pura_belanda_data: